//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharp_Day10_L10_solu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public short SalesId { get; set; }
        public decimal SalesAmt { get; set; }
        public System.DateTime SalesDate { get; set; }
        public decimal TaxAmt { get; set; }
    }
}
